n = input('digite um valor:')
print('o tipo primitivo desse valor é:', type(n))
print('É numérico? ', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiusculas?', n.isupper())
print('Está em minusculas?', n.islower())
print('Está em capitalizada?', n.istitle())
print('Só tem espaços?', n.isspace())
